import 'dart:convert';
import 'package:shared_preferences/shared_preferences.dart';
import '../models/deck_action.dart';

class StorageService {
  static const String _keyProfiles = 'vibedeck_profiles_v3';
  static const String _keyLastHost = 'vibedeck_last_host';
  static const String _keySelectedProfile = 'vibedeck_selected_profile_v3';

  static Future<void> saveProfiles(List<DeckProfile> profiles) async {
    final prefs = await SharedPreferences.getInstance();
    final jsonList = profiles.map((p) => p.toJson()).toList();
    await prefs.setString(_keyProfiles, jsonEncode(jsonList));
  }

  static Future<List<DeckProfile>> loadProfiles() async {
    final prefs = await SharedPreferences.getInstance();
    final raw = prefs.getString(_keyProfiles);
    if (raw != null) {
      try {
        final list = jsonDecode(raw) as List<dynamic>;
        return list.map((e) => DeckProfile.fromJson(Map<String, dynamic>.from(e))).toList();
      } catch (_) {}
    }
    return _getDefaultProfiles();
  }

  static Future<void> saveLastHost(String host) async {
    final prefs = await SharedPreferences.getInstance();
    await prefs.setString(_keyLastHost, host);
  }

  static Future<String?> getLastHost() async {
    final prefs = await SharedPreferences.getInstance();
    return prefs.getString(_keyLastHost);
  }

  static Future<void> saveSelectedProfileId(String id) async {
    final prefs = await SharedPreferences.getInstance();
    await prefs.setString(_keySelectedProfile, id);
  }

  static Future<String?> getSelectedProfileId() async {
    final prefs = await SharedPreferences.getInstance();
    return prefs.getString(_keySelectedProfile);
  }

  static List<DeckProfile> _getDefaultProfiles() {
    return [
      // 1. Stream Deck 32-Key XL (8 columns x 4 rows = exactly 32 keys)
      DeckProfile(
        id: 'stream_deck_32',
        name: 'Stream Deck 32-Key XL',
        columns: 8,
        rows: 4,
        buttons: [
          DeckButton(
            id: 'btn_play_pause',
            title: 'Play/Pause',
            actionType: 'media',
            payload: {'key': 'media_play_pause'},
            colorHex: '#6C5CE7',
            iconName: 'play_arrow',
          ),
          DeckButton(
            id: 'btn_prev',
            title: 'Prev Track',
            actionType: 'media',
            payload: {'key': 'media_prev'},
            colorHex: '#0984E3',
            iconName: 'skip_previous',
          ),
          DeckButton(
            id: 'btn_next',
            title: 'Next Track',
            actionType: 'media',
            payload: {'key': 'media_next'},
            colorHex: '#00CEC9',
            iconName: 'skip_next',
          ),
          DeckButton(
            id: 'btn_vol_up',
            title: 'Volume +',
            actionType: 'media',
            payload: {'key': 'volume_up'},
            colorHex: '#00B894',
            iconName: 'volume_up',
          ),
          DeckButton(
            id: 'btn_vol_down',
            title: 'Volume -',
            actionType: 'media',
            payload: {'key': 'volume_down'},
            colorHex: '#00CEC9',
            iconName: 'volume_down',
          ),
          DeckButton(
            id: 'btn_mute_master',
            title: 'Mute Master',
            actionType: 'mute',
            payload: {'key': 'volume_mute'},
            colorHex: '#D63031',
            iconName: 'volume_off',
          ),
          DeckButton(
            id: 'btn_mic_mute',
            title: 'Mic Mute',
            actionType: 'mic_mute',
            payload: {},
            colorHex: '#FF7675',
            iconName: 'mic_off',
          ),
          DeckButton(
            id: 'btn_discord_deafen',
            title: 'Deafen',
            actionType: 'discord',
            payload: {'action': 'toggle_deafen'},
            colorHex: '#5865F2',
            iconName: 'headset_off',
          ),
          DeckButton(
            id: 'btn_brave',
            title: 'Brave',
            actionType: 'app',
            payload: {'target': r'C:\Program Files\BraveSoftware\Brave-Browser\Application\brave.exe'},
            colorHex: '#FF5500',
            iconName: 'language',
          ),
          DeckButton(
            id: 'btn_spotify',
            title: 'Spotify',
            actionType: 'spotify',
            payload: {'action': 'open'},
            colorHex: '#1DB954',
            iconName: 'music_note',
          ),
          DeckButton(
            id: 'btn_discord',
            title: 'Discord',
            actionType: 'discord',
            payload: {'action': 'open'},
            colorHex: '#5865F2',
            iconName: 'forum',
          ),
          DeckButton(
            id: 'btn_obs',
            title: 'OBS Studio',
            actionType: 'app',
            payload: {'target': r'C:\Program Files\obs-studio\bin\64bit\obs64.exe'},
            colorHex: '#302E31',
            iconName: 'smart_display',
          ),
          DeckButton(
            id: 'btn_davinci',
            title: 'DaVinci',
            actionType: 'app',
            payload: {'target': r'C:\Program Files\Blackmagic Design\DaVinci Resolve\Resolve.exe'},
            colorHex: '#E74C3C',
            iconName: 'movie_edit',
          ),
          DeckButton(
            id: 'btn_steam',
            title: 'Steam',
            actionType: 'app',
            payload: {'target': 'steam:'},
            colorHex: '#171A21',
            iconName: 'sports_esports',
          ),
          DeckButton(
            id: 'btn_vscode',
            title: 'VS Code',
            actionType: 'app',
            payload: {'target': 'code'},
            colorHex: '#007ACC',
            iconName: 'code',
          ),
          DeckButton(
            id: 'btn_terminal',
            title: 'Terminal',
            actionType: 'app',
            payload: {'target': 'wt.exe'},
            colorHex: '#2D3436',
            iconName: 'terminal',
          ),
          DeckButton(
            id: 'btn_screenshot',
            title: 'Snip Tool',
            actionType: 'system',
            payload: {'command': 'screenshot'},
            colorHex: '#F39C12',
            iconName: 'crop',
          ),
          DeckButton(
            id: 'btn_taskmgr',
            title: 'Task Mgr',
            actionType: 'system',
            payload: {'command': 'task_manager'},
            colorHex: '#E74C3C',
            iconName: 'memory',
          ),
          DeckButton(
            id: 'btn_desktop',
            title: 'Desktop',
            actionType: 'system',
            payload: {'command': 'show_desktop'},
            colorHex: '#3498DB',
            iconName: 'desktop_windows',
          ),
          DeckButton(
            id: 'btn_calc',
            title: 'Calculator',
            actionType: 'app',
            payload: {'target': 'calc.exe'},
            colorHex: '#9B59B6',
            iconName: 'calculate',
          ),
          DeckButton(
            id: 'btn_notepad',
            title: 'Notepad',
            actionType: 'app',
            payload: {'target': 'notepad.exe'},
            colorHex: '#1ABC9C',
            iconName: 'description',
          ),
          DeckButton(
            id: 'btn_explorer',
            title: 'Explorer',
            actionType: 'app',
            payload: {'target': 'explorer.exe'},
            colorHex: '#F1C40F',
            iconName: 'folder_open',
          ),
          DeckButton(
            id: 'btn_alt_tab',
            title: 'Alt + Tab',
            actionType: 'system',
            payload: {'command': 'alt_tab'},
            colorHex: '#34495E',
            iconName: 'tab',
          ),
          DeckButton(
            id: 'btn_screen_off',
            title: 'Screen Off',
            actionType: 'system',
            payload: {'command': 'screen_off'},
            colorHex: '#7F8C8D',
            iconName: 'brightness_2',
          ),
          DeckButton(
            id: 'btn_bright_up',
            title: 'Bright +',
            actionType: 'system',
            payload: {'command': 'brightness_up'},
            colorHex: '#F39C12',
            iconName: 'brightness_high',
          ),
          DeckButton(
            id: 'btn_bright_down',
            title: 'Bright -',
            actionType: 'system',
            payload: {'command': 'brightness_down'},
            colorHex: '#E67E22',
            iconName: 'brightness_low',
          ),
          DeckButton(
            id: 'btn_spotify_like',
            title: 'Like Song',
            actionType: 'spotify',
            payload: {'action': 'like'},
            colorHex: '#1DB954',
            iconName: 'favorite',
          ),
          DeckButton(
            id: 'btn_spotify_shuffle',
            title: 'Shuffle',
            actionType: 'spotify',
            payload: {'action': 'shuffle'},
            colorHex: '#2ECC71',
            iconName: 'shuffle',
          ),
          DeckButton(
            id: 'btn_copy',
            title: 'Copy',
            actionType: 'hotkey',
            payload: {'keys': ['ctrl', 'c']},
            colorHex: '#95A5A6',
            iconName: 'content_copy',
          ),
          DeckButton(
            id: 'btn_paste',
            title: 'Paste',
            actionType: 'hotkey',
            payload: {'keys': ['ctrl', 'v']},
            colorHex: '#BDC3C7',
            iconName: 'content_paste',
          ),
          DeckButton(
            id: 'btn_lock',
            title: 'Lock PC',
            actionType: 'system',
            payload: {'command': 'lock'},
            colorHex: '#E74C3C',
            iconName: 'lock',
          ),
          DeckButton(
            id: 'btn_sleep',
            title: 'Sleep PC',
            actionType: 'system',
            payload: {'command': 'sleep'},
            colorHex: '#8E44AD',
            iconName: 'bedtime',
          ),
        ],
      ),

      // 2. Games & Launchers (User's PC Games & Apps)
      DeckProfile(
        id: 'games_and_apps',
        name: 'Games & Launchers',
        columns: 6,
        rows: 3,
        buttons: [
          DeckButton(
            id: 'btn_valorant',
            title: 'VALORANT',
            actionType: 'app',
            payload: {'target': r'C:\Users\Public\Desktop\VALORANT.lnk'},
            colorHex: '#FD4556',
            iconName: 'sports_esports',
          ),
          DeckButton(
            id: 'btn_nfs_heat',
            title: 'NFS Heat',
            actionType: 'app',
            payload: {'target': r'C:\Users\Public\Desktop\Play Need for Speed Heat.lnk'},
            colorHex: '#FF007F',
            iconName: 'directions_car',
          ),
          DeckButton(
            id: 'btn_ets2',
            title: 'Euro Truck 2',
            actionType: 'app',
            payload: {'target': r'C:\Program Files (x86)\Steam\steamapps\common\Euro Truck Simulator 2\bin\win_x64\eurotrucks2.exe'},
            colorHex: '#FFA500',
            iconName: 'local_shipping',
          ),
          DeckButton(
            id: 'btn_mkx',
            title: 'Mortal Kombat X',
            actionType: 'app',
            payload: {'target': r'C:\Program Files (x86)\Steam\steamapps\common\MK10\Binaries\Retail\MK10.exe'},
            colorHex: '#D4AC0D',
            iconName: 'fitness_center',
          ),
          DeckButton(
            id: 'btn_clash',
            title: 'Clash of Clans',
            actionType: 'app',
            payload: {'target': r'C:\Users\fdora\Desktop\Clash of Clans.lnk'},
            colorHex: '#FFC000',
            iconName: 'shield',
          ),
          DeckButton(
            id: 'btn_brave_browser',
            title: 'Brave',
            actionType: 'app',
            payload: {'target': r'C:\Program Files\BraveSoftware\Brave-Browser\Application\brave.exe'},
            colorHex: '#FB542B',
            iconName: 'language',
          ),
          DeckButton(
            id: 'btn_obs_studio',
            title: 'OBS Studio',
            actionType: 'app',
            payload: {'target': r'C:\Program Files\obs-studio\bin\64bit\obs64.exe'},
            colorHex: '#302E31',
            iconName: 'smart_display',
          ),
          DeckButton(
            id: 'btn_davinci_resolve',
            title: 'DaVinci Resolve',
            actionType: 'app',
            payload: {'target': r'C:\Program Files\Blackmagic Design\DaVinci Resolve\Resolve.exe'},
            colorHex: '#E74C3C',
            iconName: 'movie_edit',
          ),
          DeckButton(
            id: 'btn_steam_app',
            title: 'Steam',
            actionType: 'app',
            payload: {'target': 'steam:'},
            colorHex: '#171A21',
            iconName: 'videogame_asset',
          ),
          DeckButton(
            id: 'btn_epic_games',
            title: 'Epic Games',
            actionType: 'app',
            payload: {'target': r'C:\Program Files\Epic Games\Launcher\Portal\Binaries\Win64\EpicGamesLauncher.exe'},
            colorHex: '#333333',
            iconName: 'games',
          ),
          DeckButton(
            id: 'btn_mouse_sw',
            title: 'Mouse Software',
            actionType: 'app',
            payload: {'target': r'C:\Program Files (x86)\Fantech\PHANTOM II VX6\Gaming Mouse 3.0.exe'},
            colorHex: '#9B59B6',
            iconName: 'mouse',
          ),
          DeckButton(
            id: 'btn_nvidia_app',
            title: 'NVIDIA App',
            actionType: 'app',
            payload: {'target': r'C:\Program Files\NVIDIA Corporation\NVIDIA App\CEF\NVIDIA App.exe'},
            colorHex: '#76B900',
            iconName: 'memory',
          ),
          DeckButton(
            id: 'btn_discord_app',
            title: 'Discord',
            actionType: 'discord',
            payload: {'action': 'open'},
            colorHex: '#5865F2',
            iconName: 'forum',
          ),
          DeckButton(
            id: 'btn_spotify_app',
            title: 'Spotify',
            actionType: 'spotify',
            payload: {'action': 'open'},
            colorHex: '#1DB954',
            iconName: 'music_note',
          ),
          DeckButton(
            id: 'btn_medal_tv',
            title: 'Medal Clips',
            actionType: 'app',
            payload: {'target': r'C:\Users\fdora\AppData\Local\Medal\current\Medal.exe'},
            colorHex: '#FFBF00',
            iconName: 'videocam',
          ),
          DeckButton(
            id: 'btn_vscode_app',
            title: 'VS Code',
            actionType: 'app',
            payload: {'target': 'code'},
            colorHex: '#007ACC',
            iconName: 'code',
          ),
          DeckButton(
            id: 'btn_play_games',
            title: 'Play Games',
            actionType: 'app',
            payload: {'target': r'C:\Program Files\Google\Play Games\Bootstrapper.exe'},
            colorHex: '#008744',
            iconName: 'sports_esports',
          ),
          DeckButton(
            id: 'btn_riot_client',
            title: 'Riot Client',
            actionType: 'app',
            payload: {'target': r'C:\Riot Games\Riot Client\RiotClientServices.exe'},
            colorHex: '#D63031',
            iconName: 'gamepad',
          ),
        ],
      ),

      // 3. System & Settings (Hardware, Power, Volume, Brightness)
      DeckProfile(
        id: 'system_settings',
        name: 'System & Settings',
        columns: 6,
        rows: 3,
        buttons: [
          DeckButton(
            id: 'btn_shutdown',
            title: 'Shutdown PC',
            actionType: 'system',
            payload: {'command': 'shutdown'},
            colorHex: '#D63031',
            iconName: 'power_settings_new',
          ),
          DeckButton(
            id: 'btn_restart',
            title: 'Restart PC',
            actionType: 'system',
            payload: {'command': 'restart'},
            colorHex: '#E67E22',
            iconName: 'restart_alt',
          ),
          DeckButton(
            id: 'btn_lock_pc',
            title: 'Lock PC',
            actionType: 'system',
            payload: {'command': 'lock'},
            colorHex: '#E74C3C',
            iconName: 'lock',
          ),
          DeckButton(
            id: 'btn_sleep_pc',
            title: 'Sleep PC',
            actionType: 'system',
            payload: {'command': 'sleep'},
            colorHex: '#8E44AD',
            iconName: 'bedtime',
          ),
          DeckButton(
            id: 'btn_screen_off',
            title: 'Screen Off',
            actionType: 'system',
            payload: {'command': 'screen_off'},
            colorHex: '#34495E',
            iconName: 'brightness_2',
          ),
          DeckButton(
            id: 'btn_taskmgr',
            title: 'Task Manager',
            actionType: 'system',
            payload: {'command': 'task_manager'},
            colorHex: '#9B59B6',
            iconName: 'memory',
          ),
          DeckButton(
            id: 'btn_bright_up',
            title: 'Brightness +',
            actionType: 'system',
            payload: {'command': 'brightness_up'},
            colorHex: '#F39C12',
            iconName: 'brightness_high',
          ),
          DeckButton(
            id: 'btn_bright_down',
            title: 'Brightness -',
            actionType: 'system',
            payload: {'command': 'brightness_down'},
            colorHex: '#D35400',
            iconName: 'brightness_low',
          ),
          DeckButton(
            id: 'btn_mute',
            title: 'Master Mute',
            actionType: 'mute',
            payload: {'key': 'volume_mute'},
            colorHex: '#E74C3C',
            iconName: 'volume_off',
          ),
          DeckButton(
            id: 'btn_mic_mute',
            title: 'Mic Mute',
            actionType: 'mic_mute',
            payload: {},
            colorHex: '#FF7675',
            iconName: 'mic_off',
          ),
          DeckButton(
            id: 'btn_discord_deafen',
            title: 'Deafen',
            actionType: 'discord',
            payload: {'action': 'toggle_deafen'},
            colorHex: '#5865F2',
            iconName: 'headset_off',
          ),
          DeckButton(
            id: 'btn_screenshot',
            title: 'Snip Tool',
            actionType: 'system',
            payload: {'command': 'screenshot'},
            colorHex: '#F1C40F',
            iconName: 'crop',
          ),
          DeckButton(
            id: 'btn_vol_up',
            title: 'Volume +',
            actionType: 'media',
            payload: {'key': 'volume_up'},
            colorHex: '#00B894',
            iconName: 'volume_up',
          ),
          DeckButton(
            id: 'btn_vol_down',
            title: 'Volume -',
            actionType: 'media',
            payload: {'key': 'volume_down'},
            colorHex: '#00CEC9',
            iconName: 'volume_down',
          ),
          DeckButton(
            id: 'btn_play_pause',
            title: 'Play / Pause',
            actionType: 'media',
            payload: {'key': 'media_play_pause'},
            colorHex: '#6C5CE7',
            iconName: 'play_arrow',
          ),
          DeckButton(
            id: 'btn_prev',
            title: 'Prev Track',
            actionType: 'media',
            payload: {'key': 'media_prev'},
            colorHex: '#0984E3',
            iconName: 'skip_previous',
          ),
          DeckButton(
            id: 'btn_next',
            title: 'Next Track',
            actionType: 'media',
            payload: {'key': 'media_next'},
            colorHex: '#00CEC9',
            iconName: 'skip_next',
          ),
          DeckButton(
            id: 'btn_desktop',
            title: 'Desktop',
            actionType: 'system',
            payload: {'command': 'show_desktop'},
            colorHex: '#2980B9',
            iconName: 'desktop_windows',
          ),
        ],
      ),

      // 4. Discord Studio
      DeckProfile(
        id: 'discord_studio',
        name: 'Discord Studio',
        columns: 5,
        rows: 3,
        buttons: [
          DeckButton(
            id: 'btn_dc_mute',
            title: 'Mute Mic',
            actionType: 'discord',
            payload: {'action': 'toggle_mute'},
            colorHex: '#FF7675',
            iconName: 'mic_off',
          ),
          DeckButton(
            id: 'btn_dc_deafen',
            title: 'Deafen',
            actionType: 'discord',
            payload: {'action': 'toggle_deafen'},
            colorHex: '#D63031',
            iconName: 'headset_off',
          ),
          DeckButton(
            id: 'btn_dc_screenshare',
            title: 'Screen Share',
            actionType: 'discord',
            payload: {'action': 'screenshare'},
            colorHex: '#5865F2',
            iconName: 'screen_share',
          ),
          DeckButton(
            id: 'btn_dc_ptt',
            title: 'Push to Talk',
            actionType: 'discord',
            payload: {'action': 'push_to_talk'},
            colorHex: '#00FF88',
            iconName: 'record_voice_over',
          ),
          DeckButton(
            id: 'btn_dc_accept_call',
            title: 'Accept Call',
            actionType: 'discord',
            payload: {'action': 'accept_call'},
            colorHex: '#2ECC71',
            iconName: 'call',
          ),
          DeckButton(
            id: 'btn_dc_decline_call',
            title: 'End Call',
            actionType: 'discord',
            payload: {'action': 'decline_call'},
            colorHex: '#E74C3C',
            iconName: 'call_end',
          ),
          DeckButton(
            id: 'btn_dc_voice_general',
            title: 'Voice Room',
            actionType: 'discord',
            payload: {'action': 'join_voice', 'channel_url': 'https://discord.com/channels/@me'},
            colorHex: '#5865F2',
            iconName: 'volume_up',
          ),
          DeckButton(
            id: 'btn_dc_chat_general',
            title: 'Text Chat',
            actionType: 'discord',
            payload: {'action': 'open_channel', 'channel_url': 'https://discord.com/channels/@me'},
            colorHex: '#5865F2',
            iconName: 'chat',
          ),
          DeckButton(
            id: 'btn_dc_inbox',
            title: 'Mentions',
            actionType: 'hotkey',
            payload: {'keys': ['ctrl', 'i']},
            colorHex: '#9B59B6',
            iconName: 'alternate_email',
          ),
          DeckButton(
            id: 'btn_dc_pins',
            title: 'Pinned Msgs',
            actionType: 'hotkey',
            payload: {'keys': ['ctrl', 'p']},
            colorHex: '#F39C12',
            iconName: 'push_pin',
          ),
          DeckButton(
            id: 'btn_dc_search',
            title: 'Find / Jump',
            actionType: 'hotkey',
            payload: {'keys': ['ctrl', 'f']},
            colorHex: '#3498DB',
            iconName: 'search',
          ),
          DeckButton(
            id: 'btn_dc_emoji',
            title: 'Emoji Picker',
            actionType: 'hotkey',
            payload: {'keys': ['ctrl', 'e']},
            colorHex: '#F1C40F',
            iconName: 'mood',
          ),
          DeckButton(
            id: 'btn_dc_settings',
            title: 'Settings',
            actionType: 'hotkey',
            payload: {'keys': ['ctrl', ',']},
            colorHex: '#34495E',
            iconName: 'tune',
          ),
          DeckButton(
            id: 'btn_dc_open',
            title: 'Launch Discord',
            actionType: 'discord',
            payload: {'action': 'open'},
            colorHex: '#5865F2',
            iconName: 'forum',
          ),
          DeckButton(
            id: 'btn_dc_close',
            title: 'Quit Discord',
            actionType: 'discord',
            payload: {'action': 'close'},
            colorHex: '#7F8C8D',
            iconName: 'power_settings_new',
          ),
        ],
      ),

      // 5. Spotify Pro
      DeckProfile(
        id: 'spotify_pro',
        name: 'Spotify Pro',
        columns: 5,
        rows: 3,
        buttons: [
          DeckButton(
            id: 'btn_sp_play',
            title: 'Play / Pause',
            actionType: 'spotify',
            payload: {'action': 'play_pause'},
            colorHex: '#1DB954',
            iconName: 'play_arrow',
          ),
          DeckButton(
            id: 'btn_sp_prev',
            title: 'Prev Track',
            actionType: 'spotify',
            payload: {'action': 'prev'},
            colorHex: '#0984E3',
            iconName: 'skip_previous',
          ),
          DeckButton(
            id: 'btn_sp_next',
            title: 'Next Track',
            actionType: 'spotify',
            payload: {'action': 'next'},
            colorHex: '#00CEC9',
            iconName: 'skip_next',
          ),
          DeckButton(
            id: 'btn_sp_vol_up',
            title: 'Spotify Vol +',
            actionType: 'hotkey',
            payload: {'keys': ['ctrl', 'up']},
            colorHex: '#2ECC71',
            iconName: 'volume_up',
          ),
          DeckButton(
            id: 'btn_sp_vol_down',
            title: 'Spotify Vol -',
            actionType: 'hotkey',
            payload: {'keys': ['ctrl', 'down']},
            colorHex: '#27AE60',
            iconName: 'volume_down',
          ),
          DeckButton(
            id: 'btn_sp_shuffle',
            title: 'Shuffle',
            actionType: 'spotify',
            payload: {'action': 'shuffle'},
            colorHex: '#1DB954',
            iconName: 'shuffle',
          ),
          DeckButton(
            id: 'btn_sp_repeat',
            title: 'Repeat',
            actionType: 'spotify',
            payload: {'action': 'repeat'},
            colorHex: '#16A085',
            iconName: 'repeat',
          ),
          DeckButton(
            id: 'btn_sp_like',
            title: 'Like Song',
            actionType: 'spotify',
            payload: {'action': 'like'},
            colorHex: '#E74C3C',
            iconName: 'favorite',
          ),
          DeckButton(
            id: 'btn_sp_lofi',
            title: 'Lo-Fi Beats',
            actionType: 'spotify',
            payload: {'action': 'playlist', 'uri': 'spotify:playlist:37i9dQZF1DXdLEN7aqioXM', 'auto_play': true},
            colorHex: '#9B59B6',
            iconName: 'spa',
          ),
          DeckButton(
            id: 'btn_sp_tophits',
            title: 'Today\'s Hits',
            actionType: 'spotify',
            payload: {'action': 'playlist', 'uri': 'spotify:playlist:37i9dQZF1DXcBWIGoYBM5M', 'auto_play': true},
            colorHex: '#F39C12',
            iconName: 'trending_up',
          ),
          DeckButton(
            id: 'btn_sp_focus',
            title: 'Deep Focus',
            actionType: 'spotify',
            payload: {'action': 'playlist', 'uri': 'spotify:playlist:37i9dQZF1DWZeKCadgRdKQ', 'auto_play': true},
            colorHex: '#3498DB',
            iconName: 'psychology',
          ),
          DeckButton(
            id: 'btn_sp_gaming',
            title: 'Bass Gaming',
            actionType: 'spotify',
            payload: {'action': 'playlist', 'uri': 'spotify:playlist:37i9dQZF1DXdfOcg1KaUVg', 'auto_play': true},
            colorHex: '#E67E22',
            iconName: 'sports_esports',
          ),
          DeckButton(
            id: 'btn_sp_liked',
            title: 'Liked Songs',
            actionType: 'spotify',
            payload: {'action': 'playlist', 'uri': 'spotify:collection:tracks', 'auto_play': true},
            colorHex: '#E74C3C',
            iconName: 'favorite_border',
          ),
          DeckButton(
            id: 'btn_sp_open',
            title: 'Launch Spotify',
            actionType: 'spotify',
            payload: {'action': 'open'},
            colorHex: '#1DB954',
            iconName: 'music_note',
          ),
          DeckButton(
            id: 'btn_sp_close',
            title: 'Quit Spotify',
            actionType: 'spotify',
            payload: {'action': 'close'},
            colorHex: '#7F8C8D',
            iconName: 'power_settings_new',
          ),
        ],
      ),
    ];
  }
}
